// packages/userscript/src/helper/useInit.tsx
/* eslint-disable import/no-cycle */
import { useManga } from '../components/Manga';
import { useFab } from '../components/Fab';
import { useToast } from '../components/Toast';
import { useSiteOptions } from './useSiteOptions';
import { setToolbarButton } from './setToolbarButton';
import { sleep } from './utils';
import { defaultSpeedDial } from './defaultSpeedDial';

/**
 * 对三个样式组件和 useSiteOptions 的默认值进行封装
 *
 * @param name 站点名
 * @param defaultOptions 默认配置
 */
export const useInit = async <T extends Record<string, any>>(
  name: string,
  defaultOptions = {} as T,
) => {
  const { options, setOptions, onOptionChange } = await useSiteOptions(
    name,
    defaultOptions,
  );

  const setFab = useFab({
    tip: '阅读模式',
    speedDial: defaultSpeedDial(options, setOptions),
  });
  onOptionChange(() => setFab());

  const [setManga, mangaProps] = useManga({
    imgList: [],
    option: options.option,
    onOptionChange: (option) => setOptions({ ...options, option }),
  });

  const toast = useToast();

  // 对 GM.xmlHttpRequest 进行包装
  type RequestOptions = Partial<Tampermonkey.Request<any>> & {
    errorText?: string;
  };
  const request = async (
    method: 'GET' | 'POST',
    url: string,
    details?: RequestOptions,
    errorNum = 0,
  ): Promise<Tampermonkey.Response<any>> => {
    const errorText = details?.errorText ?? '漫画图片加载出错';
    try {
      const res = await GM.xmlHttpRequest({ method, url, ...details });
      if (res.status !== 200 || !res.responseText) throw new Error(errorText);
      return res;
    } catch (error) {
      if (errorNum > 3) {
        toast.error(errorText);
        throw new Error(errorText);
      }
      console.error(errorText, error);
      await sleep(1000 * 3);
      return request(method, url, details, errorNum + 1);
    }
  };

  // 检查脚本的版本变化，提示用户
  const version = await GM.getValue<string>('Version');
  if (version && version !== GM.info.script.version) {
    // FIXME: 实现通过 jsdelivr 获取指定版本的更新内容
    //     const changelog = `
    // ## 新增

    // - 通过 M 键切换页面填充

    // ## 修复

    // - 增加拷贝漫画的支持域名
    // - 修复漫画柜失效问题
    // `;
    (async () => {
      const res = await GM.xmlHttpRequest({
        method: 'GET',
        url: `https://cdn.jsdelivr.net/gh/hymbz/ComicReadScriptTest@${GM.info.script.version}/file`,
      });
      if (!res.responseText) return;
      toast(() => (
        <div>
          <h2>ComicReadScrip 已更新到 {GM.info.script.version}</h2>
          <div className="md">
            {res.responseText.match(/##.+?\n|(-.+?\n)+/g)!.map((mdText) => {
              if (mdText[0] === '#') return <h2>{mdText.split('##')}</h2>;
              if (mdText[0] === '-')
                return (
                  <ul>
                    {mdText.match(/(?<=- ).+/g)!.map((item) => (
                      <li>{item}</li>
                    ))}
                  </ul>
                );
              return null;
            })}
          </div>
        </div>
      ));
      GM_setValue('Version', GM.info.script.version);
    })();
  }

  let menuId: number;
  const updateHideFabMenu = async () => {
    await GM.unregisterMenuCommand(menuId);
    menuId = await GM.registerMenuCommand(
      `${options.hiddenFAB ? '显示' : '隐藏'}阅读模式按钮`,
      async () => {
        await setOptions({ ...options, hiddenFAB: !options.hiddenFAB });
        setFab((draftProps) => {
          draftProps.show = !options.hiddenFAB && undefined;
        });
        await updateHideFabMenu();
      },
    );
  };

  return {
    options,
    setOptions,
    onOptionChange,
    setFab,
    setManga,
    toast,

    request,

    /**
     * 创建一个加载图片列表并进入阅读模式的函数
     *
     * @param getImgList 返回图片列表的函数
     * @param onLoading 图片加载状态发生变化时触发的回调
     */
    createShowComic: (
      getImgList: () => Promise<string[]> | string[],
      onLoading: (
        loadNum: number,
        totalNum: number,
        img: ComicImg,
      ) => void = () => {},
    ) => {
      /** 是否正在加载图片中 */
      let loading = false;

      /**
       * 进入阅读模式
       */
      const showComic = async () => {
        if (loading) {
          toast('加载图片中，请稍候', { autoClose: 1500 });
          return;
        }

        const { imgList } = mangaProps;

        if (!imgList.length) {
          loading = true;
          try {
            setFab({ progress: 0, show: true });
            const initImgList = await getImgList();
            if (initImgList.length === 0) throw new Error('获取漫画图片失败');
            setFab({
              progress: 1,
              tip: '阅读模式',
              show: !options.hiddenFAB && undefined,
            });
            setManga((draftProps) => {
              draftProps.imgList = initImgList;
              draftProps.show = options.autoShow;
              setToolbarButton(draftProps);

              // 监听图片加载状态，将进度显示到 Fab 上
              draftProps.onLoading = (img, list) => {
                const loadNum = list.filter(
                  (image) => image.loadType === 'loaded',
                ).length;

                onLoading(loadNum, list.length, img);

                /** 图片加载进度 */
                const progress = 1 + loadNum / list.length;
                if (progress !== 2) {
                  setFab({
                    progress,
                    tip: `图片加载中 - ${loadNum}/${list.length}`,
                  });
                } else {
                  // 图片全部加载完成后恢复 Fab 状态
                  setFab({ progress, tip: '阅读模式', show: undefined });
                }
              };

              return draftProps;
            });
          } catch (e: any) {
            console.error(e);
            toast.error(e.message);
            setFab({ progress: undefined });
          } finally {
            loading = false;
          }
        } else {
          setManga({ show: true });
        }
      };

      // eslint-disable-next-line @typescript-eslint/no-floating-promises
      GM.registerMenuCommand('进入漫画阅读模式', showComic);
      // eslint-disable-next-line @typescript-eslint/no-floating-promises
      updateHideFabMenu();

      return showComic;
    },
  };
};

// src/helper/useInit.tsx
import { For } from 'solid-js';
import { getKeyboardCode, isEqualArray } from '.';
import { useManga } from '../components/useComponents/Manga';
import { useFab } from '../components/useComponents/Fab';
import { toast } from '../components/useComponents/Toast';
import type { SiteOptions } from './useSiteOptions';
import { useSiteOptions } from './useSiteOptions';
import { useSpeedDial } from './useSpeedDial';

/**
 * 对基础的初始化操作的封装
 * @param name 站点名
 * @param defaultOptions 默认配置
 */
export const useInit = async <T extends Record<string, any>>(
  name: string,
  defaultOptions = {} as T,
) => {
  const { options, setOptions, readModeHotKeys, hotKeys, onHotKeysChange } =
    await useSiteOptions(name, defaultOptions);

  const [setFab, fabProps] = await useFab({
    tip: '阅读模式',
    speedDial: useSpeedDial(options, setOptions),
    show: !options.hiddenFAB && undefined,
  });

  /** 处理 Manga 组件的 onLoading 回调，将图片加载状态联动到 Fab 上 */
  const onLoading = (list: ComicImg[]) => {
    const loadNum = list.filter((image) => image.loadType === 'loaded').length;

    /** 图片加载进度 */
    const progress = 1 + loadNum / list.length;
    if (progress !== 2) {
      setFab({
        progress,
        tip: `图片加载中 - ${loadNum}/${list.length}`,
      });
    } else {
      // 图片全部加载完成后恢复 Fab 状态
      setFab({ progress, tip: '阅读模式', show: undefined });
    }
  };

  const [setManga, mangaProps] = await useManga({
    imgList: [],
    option: options.option,
    onOptionChange: (option) =>
      setOptions({ option } as Partial<T & SiteOptions>),
    hotKeys: hotKeys(),
    onHotKeysChange,
    onLoading,
  });

  // 检查脚本的版本变化，提示用户
  const version = await GM.getValue<string>('Version');
  if (version && version !== GM.info.script.version) {
    const latestChange = inject('LatestChange');
    toast(
      () => (
        <>
          <h2>🥳 ComicRead 已更新到 v{GM.info.script.version}</h2>
          <div>
            <For each={latestChange.match(/^### [^[].+?$|^\* .+?$/gm)}>
              {(mdText) => {
                switch (mdText[0]) {
                  case '#':
                    return <h3>{mdText.replace('### ', '')}</h3>;
                  case '*':
                    return (
                      <ul>
                        <li>
                          {mdText
                            .replace(/^\* /, '')
                            .replace(/^:\w+?: /, '')
                            .replace(/(?<=^.*)\(\[\w+\]\(.+?\)\)/, '')}
                        </li>
                      </ul>
                    );
                  default:
                    return null;
                }
              }}
            </For>
          </div>
        </>
      ),
      {
        id: 'Version Tip',
        type: 'custom',
        duration: Infinity,
        // 手动点击关掉通知后才不会再次弹出
        onDismiss: () => GM.setValue('Version', GM.info.script.version),
      },
    );

    // 监听储存的版本数据的变动，如果和当前版本一致就关掉弹窗
    // 防止在更新版本后一次性打开多个页面，不得不一个一个关过去
    const listenerId = await GM.addValueChangeListener(
      'Version',
      async (_, __, newVersion) => {
        if (newVersion !== GM.info.script.version) return;
        toast.dismiss('Version Tip');
        await GM.removeValueChangeListener(listenerId);
      },
    );
  }

  let menuId: number;
  /** 更新显示/隐藏悬浮按钮的菜单项 */
  const updateHideFabMenu = async () => {
    await GM.unregisterMenuCommand(menuId);
    menuId = await GM.registerMenuCommand(
      `${options.hiddenFAB ? '显示' : '隐藏'}悬浮按钮`,
      async () => {
        await setOptions({ ...options, hiddenFAB: !options.hiddenFAB });
        setFab((state) => {
          state.show = !options.hiddenFAB && undefined;
        });
        await updateHideFabMenu();
      },
    );
  };

  /** 当前是否还需要判断 autoShow */
  const needAutoShow = { val: true };

  return {
    options,
    setOptions,
    setFab,
    setManga,
    mangaProps,
    needAutoShow,

    /**
     * 对 加载图片 和 进入阅读模式 相关初始化的封装
     * @param getImgList 返回图片列表的函数
     * @returns 自动加载图片并进入阅读模式的函数
     */
    init: (getImgList: () => Promise<string[]> | string[]) => {
      const firstRun = menuId === undefined;

      /** 是否正在加载图片中 */
      let loading = false;

      /** 加载 imgList */
      const loadImgList = async (initImgList?: string[], show?: boolean) => {
        loading = true;
        try {
          if (!initImgList) setFab({ progress: 0, show: true });
          const newImgList = initImgList ?? (await getImgList());
          if (newImgList.length === 0) throw new Error('获取漫画图片失败');
          setManga((state) => {
            if (!isEqualArray(newImgList, mangaProps.imgList))
              state.imgList = [...newImgList];
            if (show || (needAutoShow.val && options.autoShow)) {
              state.show = true;
              needAutoShow.val = false;
            }
          });
        } catch (e: any) {
          console.error(e);
          if (show) toast.error(e.message);
          setFab({ progress: undefined });
        } finally {
          loading = false;
        }
      };

      /** 进入阅读模式 */
      const showComic = async () => {
        if (loading)
          return toast.warn('加载图片中，请稍候', { duration: 1500 });

        if (!mangaProps.imgList.length) return loadImgList(undefined, true);

        setManga({ show: true });
      };

      setFab({ onClick: showComic });

      if (needAutoShow.val && options.autoShow) showComic();

      if (firstRun) {
        GM.registerMenuCommand('进入漫画阅读模式', fabProps.onClick!);
        updateHideFabMenu();

        window.addEventListener('keydown', (e) => {
          if ((e.target as HTMLElement).tagName === 'INPUT') return;
          const code = getKeyboardCode(e);
          if (!readModeHotKeys().has(code)) return;
          e.stopPropagation();
          e.preventDefault();
          fabProps.onClick?.();
        });
      }

      return {
        /** 进入阅读模式 */
        showComic,
        /** 加载 imgList */
        loadImgList,
        /** Manga 组件的默认 onLoading */
        onLoading,
      };
    },
  };
};
