// packages/solid-ui/src/containers/Manga/components/Scrollbar.tsx
import type { Component } from 'solid-js';
import { Show, For } from 'solid-js';
import { store } from '../hooks/useStore';
import { handleWheel } from '../hooks/useStore/slice';
import { useDrag } from '../hooks/useDrag';

import classes from '../index.module.css';

/** 滚动条上用于显示对应图片加载情况的元素 */
const ScrollbarPage: Component<{ index: number }> = (props) => (
  <div
    class={classes.scrollbarPage}
    data-index={props.index}
    data-type={store.imgList[props.index].loadType}
  />
);

/** 滚动条 */
export const Scrollbar: Component = () => (
  <div
    ref={useDrag}
    class={classes.scrollbar}
    classList={{
      [classes.hidden]: !store.option.scrollbar.enabled && !store.showScrollbar,
    }}
    role="scrollbar"
    aria-controls={classes.mangaFlow}
    aria-valuenow={store.activePageIndex || -1}
    tabIndex={-1}
    onWheel={handleWheel}
  >
    <div
      class={classes.scrollbarDrag}
      data-show={!store.option.scrollbar.autoHidden || store.showScrollbar}
      style={{
        top: store.option.scrollMode
          ? `${store.scrollbar.dragTop * 100}%`
          : `${(1 / store.pageList.length) * 100 * store.activePageIndex}%`,
        height: store.scrollbar.dragHeight
          ? `${store.scrollbar.dragHeight * 100}%`
          : `${(1 / store.pageList.length) * 100}%`,
      }}
    >
      <div
        class={classes.scrollbarPoper}
        classList={{ [classes.hidden]: !store.scrollbar.tipText }}
        data-show={store.showScrollbar}
      >
        {store.scrollbar.tipText}
      </div>
    </div>

    <Show when={store.option.scrollbar.showProgress}>
      <For each={store.pageList}>
        {([a, b]) => (
          <div>
            <ScrollbarPage index={a !== -1 ? a : b!} />
            {b ? <ScrollbarPage index={b !== -1 ? b : a} /> : null}
          </div>
        )}
      </For>
    </Show>
  </div>
);

// packages/ui-component/src/containers/Manga/components/Scrollbar.tsx
import clsx from 'clsx';
import type { CSSProperties } from 'react';
import { useRef, memo, useMemo } from 'react';
import { useDrag } from '../hooks/useDrag';
import type { SelfState } from '../hooks/useStore';
import { shallow, useStore } from '../hooks/useStore';

import classes from '../index.module.css';
import { ScrollbarPage } from './ScrollbarPage';

const selector = ({
  option: { scrollbar, scrollMode },
  pageList,
  showScrollbar,
  activePageIndex,
  scrollbar: { dragHeight, dragTop, handleWheel, dragOption, tipText },
}: SelfState) => ({
  pageList,
  showScrollbar,
  scrollbar,
  scrollMode,
  activePageIndex,
  dragHeight,
  dragTop,
  handleWheel,
  dragOption,
  tipText,
});

/** 滚动条 */
export const Scrollbar: React.FC = memo(() => {
  const {
    pageList,
    showScrollbar,
    scrollbar,
    scrollMode,
    activePageIndex,
    dragHeight,
    dragTop,
    handleWheel,
    dragOption,
    tipText,
  } = useStore(selector, shallow);

  const style = useMemo(
    () =>
      ({
        '--pageHeight': `${(1 / pageList.length) * 100}%`,
      } as CSSProperties),
    [pageList.length],
  );

  const pageEleList = useMemo(
    () =>
      scrollbar.showProgress
        ? pageList.map(([a, b]) => (
            <div key={`${a.index}${b?.index}`}>
              <ScrollbarPage index={a.index} />
              {b ? <ScrollbarPage index={b.index} /> : null}
            </div>
          ))
        : [],
    [scrollbar.showProgress, pageList],
  );

  const ref = useRef<HTMLDivElement>(null);
  useDrag(ref, dragOption);

  return (
    <div
      ref={ref}
      className={clsx(classes.scrollbar, {
        [classes.hidden]: !scrollbar.enabled && !showScrollbar,
      })}
      role="scrollbar"
      aria-controls={classes.mangaFlow}
      aria-valuenow={activePageIndex || -1}
      style={style}
      tabIndex={-1}
      onWheel={handleWheel}
    >
      <div
        className={classes.scrollbarDrag}
        data-show={!scrollbar.autoHidden || showScrollbar}
        style={{
          transform: scrollMode
            ? undefined
            : `translateY(${activePageIndex}00%)`,
          top: `${dragTop * 100}%`,
          height: dragHeight ? `${dragHeight * 100}%` : undefined,
        }}
      >
        <div
          className={clsx(classes.scrollbarPoper, !tipText && classes.hidden)}
          data-show={showScrollbar}
        >
          {tipText}
        </div>
      </div>

      {pageEleList}
    </div>
  );
});
