// packages/ui-component/src/containers/Manga/components/ComicImg.tsx
import type { Draft } from 'immer';
import { current } from 'immer';
import type { SyntheticEvent } from 'react';
import { memo, useRef, useCallback } from 'react';
import { shallow, useStore } from '../hooks/useStore';

import classes from '../index.module.css';

/**
 * 漫画图片
 *
 * @param img 图片数据
 */
export const ComicImg: React.FC<{ index: number }> = memo(({ index }) => {
  const imgRef = useRef<HTMLImageElement>(null);

  const handleImgLoaded = useCallback(() => {
    if (index === -1) return;
    useStore.setState((state) => {
      if (!imgRef.current) return;

      const img = state.imgList[index];
      img.loadType = 'loaded';
      img.height = imgRef.current.naturalHeight;
      img.width = imgRef.current.naturalWidth;
      state.img.updateImgType(img);

      // eslint-disable-next-line @typescript-eslint/no-floating-promises
      state.onLoading?.(current(img), current(state.imgList));
    });
  }, [index]);

  const handleImgError = useCallback(
    (e: SyntheticEvent<HTMLImageElement, Event>) => {
      if (index === -1) return;
      // 跳过因为 src 为空导致的错误
      if ((e.target as HTMLImageElement).getAttribute('src') === '') return;
      useStore.setState((state) => {
        const img = state.imgList[index];
        img.loadType = 'error';
        img.error = e as Draft<SyntheticEvent<HTMLImageElement, Event>>;
        console.error('图片加载失败', e);

        // eslint-disable-next-line @typescript-eslint/no-floating-promises
        state.onLoading?.(current(img), current(state.imgList));
      });
    },
    [index],
  );

  const { show, fill } = useStore((state) => {
    // 卷轴模式下全部显示
    if (state.option.scrollMode) return { show: '' };

    const activePage = state.pageList[state.activePageIndex];
    if (!activePage.includes(index)) return { show: undefined };
    return {
      show: '',
      fill: ((): undefined | 'left' | 'right' => {
        const i = activePage.indexOf(-1);
        if (i === -1) return undefined;
        return !!i === (state.option.dir === 'rtl') ? 'left' : 'right';
      })(),
    };
  }, shallow);

  const img = useStore((state) => state.imgList[index]);

  return (
    <img
      ref={imgRef}
      className={classes.img}
      src={img.loadType === 'wait' ? '' : img.src}
      alt={`${index}`}
      data-show={show}
      data-type={img.type}
      data-load-type={img.loadType}
      data-fill={fill}
      onLoad={handleImgLoaded}
      onError={handleImgError}
    />
  );
});

// src/components/Manga/components/ComicImg.tsx
import type { Component } from 'solid-js';
import { createMemo } from 'solid-js';

import { t } from 'helper/i18n';
import { log } from 'helper/logger';
import type { State } from '../hooks/useStore';
import { setState, store } from '../hooks/useStore';
import { updateImgType } from '../hooks/useStore/slice';
import { isWideImg } from '../handleComicData';

import classes from '../index.module.css';

export interface ComicImgProps {
  index: number;
  fill?: undefined | 'left' | 'right';
}

/** 检查已加载图片中是否**连续**出现了多个指定类型的图片 */
const checkImgTypeCount = (
  state: State,
  fn: (img: ComicImg) => boolean,
  maxNum = 3,
) => {
  let num = 0;
  for (let i = 0; i < state.imgList.length; i++) {
    const img = state.imgList[i];
    if (img.loadType !== 'loaded') continue;
    if (!fn(img)) {
      num = 0;
      continue;
    }
    num += 1;
    if (num >= maxNum) return true;
  }
  return false;
};

/** 图片加载完毕的回调 */
const handleImgLoaded = (i: number, e: HTMLImageElement) => {
  setState((state) => {
    const img = state.imgList[i];
    if (!img) return;
    if (img.loadType === 'error' && e.src !== img.src) return;
    img.loadType = 'loaded';
    img.height = e.naturalHeight;
    img.width = e.naturalWidth;
    updateImgType(state, img);
    state.onLoading?.(state.imgList, img);
    // 因为火狐浏览器在图片进入视口前，即使已经加载完了也不会对图片进行解码
    // 所以需要手动调用 decode 提前解码，防止在翻页时闪烁
    e.decode();

    switch (img.type) {
      // 连续出现多张跨页图后，将剩余未加载图片类型设为跨页图
      case 'long':
      case 'wide': {
        if (!state.flag.autoWide || !checkImgTypeCount(state, isWideImg))
          return;
        state.imgList.forEach((comicImg, index) => {
          if (comicImg.loadType === 'wait' && comicImg.type === '')
            state.imgList[index].type = 'wide';
        });
        state.flag.autoWide = false;
        break;
      }

      // 连续出现多张长图后，自动开启卷轴模式
      case 'vertical': {
        if (
          !state.flag.autoScrollMode ||
          !checkImgTypeCount(state, (image) => image.type === 'vertical')
        )
          return;
        state.option.scrollMode = true;
        state.flag.autoScrollMode = false;
        break;
      }
    }
  });
};

/** 图片加载出错的回调 */
const handleImgError = (i: number, e: HTMLImageElement) => {
  // 跳过因为 src 为空导致的错误
  if (e.getAttribute('src') === '') return;
  setState((state) => {
    const img = state.imgList[i];
    if (!img) return;

    img.loadType = 'error';
    log.error(t('alert.img_load_failed'), e);

    state.onLoading?.(state.imgList, img);
  });
};

/** 漫画图片 */
export const ComicImg: Component<ComicImgProps> = (props) => {
  const img = createMemo(() => store.imgList[props.index]);

  const src = createMemo(() => {
    if (!img() || img().loadType === 'wait') return '';
    if (img().translationType === 'show') return img().translationUrl;
    return img().src;
  });

  return (
    <img
      class={classes.img}
      style={{
        '--width': img()?.width ? `min(100%, ${img()?.width}px)` : undefined,
      }}
      src={src()}
      alt={`${props.index + 1}`}
      data-fill={props.index === -1 ? 'page' : props.fill}
      data-type={img()?.type || undefined}
      data-load-type={
        img()?.loadType === 'loaded' ? undefined : img()?.loadType
      }
      onLoad={(e) => handleImgLoaded(props.index, e.currentTarget)}
      onError={(e) => handleImgError(props.index, e.currentTarget)}
    />
  );
};
